/* Copyright 2020 petrvden */

#pragma once

#include "config_common.h"


#define PERMISSIVE_HOLD


#define MK_KINETIC_SPEED
#define MOUSEKEY_DELAY              5
#define MOUSEKEY_INTERVAL           10
#define MOUSEKEY_MOVE_DELTA         16
#define MOUSEKEY_INITIAL_SPEED      10
#define MOUSEKEY_DECELERATED_SPEED  10
#define MOUSEKEY_BASE_SPEED         5000
#define MOUSEKEY_ACCELERATED_SPEED  4800
#define MOUSEKEY_WHEEL_INITIAL_MOVEMENTS 		16
#define MOUSEKEY_WHEEL_BASE_MOVEMENTS 			128
#define MOUSEKEY_WHEEL_ACCELERATED_MOVEMENTS 	48
#define MOUSEKEY_WHEEL_DECELERATED_MOVEMENTS 	8



#define SPLIT_HAND_PIN_LOW_IS_LEFT


#define SPLIT_CONNECTION_CHECK_TIMEOUT 1000
#define SPLIT_TRANSPORT_MIRROR
